config/routes.rb
NoCms::JobOffers::Engine.routes.draw do
  resources :job_offers, only: [:index, :show] do
    resources :applicants, only: [:create]
  end
end

app/models/no_cms/job_offers/applicant.rb
module NoCms::JobOffers
  class Applicant < ActiveRecord::Base
    belongs_to :job_offer, class_name: 'NoCms::JobOffers::JobOffer', inverse_of: :applicants
    validates :name, :job_offer, presence: true
  end
end

app/models/no_cms/job_offers/concerns/globalize_slugs.rb
module NoCms::JobOffers::Concerns
  module GlobalizeSlugs
    extend ActiveSupport::Concern

    included do
    end

    # FriendlyId method
    def should_generate_new_friendly_id?
      translation_for(::Globalize.locale).send(friendly_id_config.slug_column).blank?
    end

    # Set slugs in each translation
    def set_slug normalized_slug = nil
      translations.each { |t| ::Globalize.with_locale(t.locale) { super } }
    end
  end
end

app/models/no_cms/job_offers/concerns/translation_scopes.rb
module NoCms
  module JobOffers
    module Concerns
      module TranslationScopes
        extend ActiveSupport::Concern

        included do
          scope :where_with_locale, ->(where_params, locale = ::I18n.locale) {
            with_translations(locale).where(self::Translation.table_name => where_params)
          }
        end

      end
    end
  end
end

app/models/no_cms/job_offers/job_offer.rb
module NoCms::JobOffers
  class JobOffer < ActiveRecord::Base

    include  NoCms::JobOffers::Concerns::TranslationScopes

    translates :title, :description, :slug, :draft

    extend FriendlyId
    friendly_id :title, use: [:globalize]
    include Concerns::GlobalizeSlugs

    has_many :applicants, class_name: 'NoCms::JobOffers::Applicant', inverse_of: :job_offer

    scope :drafts, ->() { where_with_locale(draft: true) }
    scope :no_drafts, ->() { where_with_locale(draft: false) }

    validates :title, :description, presence: true
  end
end

app/controllers/no_cms/job_offers/applicants_controller.rb
module NoCms::JobOffers
  class ApplicantsController < ApplicationController

    def create
      @job_offer = NoCms::JobOffers::JobOffer.includes(:translations).friendly.find params[:job_offer_id]
      @applicant = @job_offer.applicants.create applicant_params

      render 'no_cms/job_offers/job_offers/show'
    end

    def applicant_params
      params.require(:applicant).permit(:name, :position, :message)
    end

  end
end

app/controllers/no_cms/job_offers/application_controller.rb
module NoCms::JobOffers
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/no_cms/job_offers/job_offers_controller.rb
module NoCms::JobOffers
  class JobOffersController < ApplicationController
    def index
      @job_offers = NoCms::JobOffers::JobOffer.no_drafts.includes(:translations).all
    end

    def show
      @job_offer = NoCms::JobOffers::JobOffer.no_drafts.includes(:translations).friendly.find params[:id]
      @applicant = @job_offer.applicants.build
    end
  end
end

app/views/no_cms/job_offers/applicants/_form.html.erb
<%= form_for [ job_offer, applicant] do |f| %>
  <div class="row">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="row">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="row">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <%= f.submit t('.submit') %>

<% end %>

app/views/no_cms/job_offers/job_offers/index.html.erb
<h1><%= t '.job_offers_title' %></h1>
<ul>
  <% @job_offers.each do |job_offer| %>
    <li>
      <h2><%= job_offer.title %></h2>
      <%= raw job_offer.description %>
      <%= link_to t('.read_more', title: job_offer.title), job_offer_path(job_offer) %>
    </li>
  <% end -%>
</ul>

app/views/no_cms/job_offers/job_offers/show.html.erb
<h1><%= @job_offer.title %></h1>
<%= raw @job_offer.description %>

<%= render 'no_cms/job_offers/applicants/form', job_offer: @job_offer, applicant: @applicant if @applicant.new_record? %>